### ISSUE TITLE
Namensgebung

### ISSUE THREAD

**Issue by Linggify** [AGameProject/AGame#30]
@toterhaser ich bin mir nicht zu 100% sicher, aber ich denke du heißt auf deinem heim pc grammedar. wenn das so ist, dann geht dieser post hier an dich: Richtige Namensgebung von Dateien ist wichtig, und auch wichtig ist, dass man sie bitte bitte in einen nach ihm benannten Ordner legt und nicht einfach nur so in irgendeinen anderen Ordner reinschmeißt und Untitled oder Dildo nennt. Du hast von jetzt ab eine Woche zeit deinem "Dildo" einen Ordner zu machen und ihn da rein zu legen (so wie alle anderen das auch machen, in deinem Fall wäre der dann warscheinlich im Ordner characters und hieße Dildo) ooder ich lösch es einfach. Zusätzlich möchte ich festhalten, dass man bitte ernsthafte namen gibt, und unmissverständliche. Also NIEMALS eine datei untitled nennen. Und Mädchenschwert find ich als Namen eigentlich ok. ABER NICHT DILDO. NICHT NUR WEILS KEIN DILDO IST!

Danke für ihre Aufmerksamkeit

**Comment by Linggify** [comment]
Dildo is jetz weg.

**Comment by Linggify** [comment]
ah und weil das hier noch das schöne namensgebungs issue is: ein etwas ernsthafteres problem jetzt.
momentan betrifft es glaube ich nur @ConstTheFirst  aber auch für alle anderen ist das wichtig. also bitte ALLE darauf achten. Umlaute wie ä, ö ü oder auch andere Buchstaben wie ß sind als dateiname okay. aber sobald es ums programmieren geht, ist es leider ÜBERHAUPT NICHT GUT. es wäre cool wenn ihr innerhalb der Blender dateien alles mit z.b. ae, ue, oe schreibt, damit nicht ganz komische zeichen dastehen... ich hab das gemerkt als ich mir das Mauerstück mit Tür angeschaut hab in JmE und hab das da dann enttäuscht festgestellt dass der JmE umlaute anscheinent nicht so liegen.. (als Meshname als Dateiname schon ok)

LG Frederik

**Comment by ConstTheFirst** [comment]
Sorry ändere es gleich!!!

**Comment by ConstTheFirst** [comment]
Wer hat eigentlich "TURMI" gemacht und nicht ordentlich eingeordnet??
