### ISSUE TITLE
PRODUKTIVITÄT!!!!!!!!!!!

### ISSUE THREAD

**Issue by TheLastLeo** [AGameProject/AGame#35]
WARUM MACHT IHR NICHTS!!!!!!
MORGEN IST MITTWOCH UND ICH WILL DAS BIS DAHIN JEDER MINDESTENS EINEN COMITT MACHT!!!!

UND NEIN; DAS IST KEIN CAPS LOCKED; DAS IST EIN KRAMPF IM KLEINEN FINGER :)

**Comment by moeex** [comment]
Bin gespannt was du commitest ;) ;)

**Comment by TheLastLeo** [comment]
oha xD

**Comment by TheLastLeo** [comment]
damit versaust du mir den abend :[

**Comment by moeex** [comment]
Ach was da kommt bestimmt was tolles raus :+1: :+1:

**Comment by TheLastLeo** [comment]
Tanne gefällig? :)
![lp_tanne](https://cloud.githubusercontent.com/assets/9078871/6134340/d72ed608-b160-11e4-9bc3-b42c3d22d543.JPG)

**Comment by moeex** [comment]
ach du meinst ich soll jetzt noch was comitten? :D

**Comment by TheLastLeo** [comment]
JEDER!!!!!!!


MUSS!! NICHT SOLL!!!!!

**Comment by moeex** [comment]
tja.. ich glaube das wird für die meisten nichtsmehr, ich habe nichts zu comitten,
David und Zheng gucken eher unwahrscheinlich noch rein und.. 
was genau erwartest du - das wir spontan jetzt noch scheiße modelieren?
die am ende unnötig ist? Ich comitte hier doch keinen unabgesprochenen mist nur damit ich was habe, wenn dann mach ich morgen in blender nochmal was :) 
hoffe das ist auch in ordnung.

**Comment by TheLastLeo** [comment]
xD   :)



~Issue closed~
