### ISSUE TITLE
Blender 2.74 ;)

### ISSUE THREAD

**Issue by TheLastLeo** [AGameProject/AGame#36]
Meine Top neuen Dinge in 2.74 :+1:

![undo](https://cloud.githubusercontent.com/assets/9078871/6651136/563f67c2-ca35-11e4-9b35-d8b20943b0f1.JPG)
![background_images](https://cloud.githubusercontent.com/assets/9078871/6651125/56053c5a-ca35-11e4-907d-eb7bbf978018.JPG)
_____________
SSAO und DoF im Viewport!
![ao dof](https://cloud.githubusercontent.com/assets/9078871/6651124/56031182-ca35-11e4-974c-9530ccaa47fc.JPG)
______________
Cycles Pointiness Node:
![cycles pointiness](https://cloud.githubusercontent.com/assets/9078871/6651126/560e4930-ca35-11e4-9e25-849ef560665b.JPG)
------------------------------
![edge slide uvs](https://cloud.githubusercontent.com/assets/9078871/6651127/561017d8-ca35-11e4-8a3e-28c29fa1955a.JPG)
_____________
![ge1](https://cloud.githubusercontent.com/assets/9078871/6651128/561194be-ca35-11e4-9118-b55885c1b7e6.JPG)
![ge2](https://cloud.githubusercontent.com/assets/9078871/6651129/561343cc-ca35-11e4-9396-631cb89c9e2b.JPG)
_____________
![hook modifier](https://cloud.githubusercontent.com/assets/9078871/6651132/5630b420-ca35-11e4-974c-35e785a919ad.JPG)
------------------------------
![particles summary](https://cloud.githubusercontent.com/assets/9078871/6651134/5632e5ba-ca35-11e4-8ef2-f09b7e3bd75e.JPG)
z.B.:
![particle disable](https://cloud.githubusercontent.com/assets/9078871/6651133/5630f322-ca35-11e4-8bd0-43ab2115e838.JPG)
------------------------------
![spiral hair](https://cloud.githubusercontent.com/assets/9078871/6651135/5636e192-ca35-11e4-9242-4dd8f357c1c2.JPG)
------------------------------
![hair curvesa](https://cloud.githubusercontent.com/assets/9078871/6651130/56214968-ca35-11e4-891b-a86e2776b325.JPG)
------------------------------
![hair mesh](https://cloud.githubusercontent.com/assets/9078871/6651131/5623c184-ca35-11e4-9ba8-fbe513c44dce.JPG)
------------------------------

Schon geil, oder? :D

**Comment by ConstTheFirst** [comment]
:+1:

**Comment by Linggify** [comment]
ich persöhnlich finde das mit dem pointiness am tollsten.. macht ne ozean in cycles evtl cooler (ich hab ja keine ahnung wie man das sons als gemacht hat, aber ich denk das is ganz praktisch auch für so zeug..
