### ISSUE TITLE
Jakob's Errungenschaften

### ISSUE THREAD

**Issue by KeksSchnittchen** [AGameProject/AGame#37]
Die Dokumention des Lernens des Jakobus.

**Comment by KeksSchnittchen** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9078651/6825037/8a13fb88-d2f7-11e4-8fe9-14f5cd7e5368.jpg)
Mastershield

**Comment by moeex** [comment]
*like*

**Comment by moeex** [comment]
nice

**Comment by ConstTheFirst** [comment]
Menno

**Comment by Linggify** [comment]
sry es hieß nich dass es doof is.. aber die ganzen offenen issues die letztendlich nich groß was mit unserem projekt zutun haben und einfach nur kurz offen sind und dann keiner mehr verwendet regen mmich ein bisschen auf.. wenn se offen sind

**Comment by ConstTheFirst** [comment]
Ja klar, Verstehe ich natürlich.

**Comment by TheLastLeo** [comment]
http://whoblend.tumblr.com/post/95270743921
